# Generated by Django 2.2.2 on 2019-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='test', max_length=150, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
